---
? ''
: - ttl: 0
    type: A
    values:
    - 188.165.200.10
    - 37.187.74.34
    - 176.9.116.19
  - ttl: 0
    type: AAAA
    values:
    - '2001:41d0:2:910a::1'
    - '2001:41d0:a:2a22::1'
    - '2a01:4f8:151:64ec::2'
  - ttl: 0
    type: MX
    values:
    - exchange: mail.protonmail.ch.
      preference: 10
    - exchange: mailsec.protonmail.ch.
      preference: 20
  - ttl: 0
    type: NS
    values:
    - dns18.ovh.net.
    - ns18.ovh.net.
  - ttl: 0
    type: TXT
    values:
    - google-site-verification=Ygf2n9qWhHEWR1d8kYayfaS91qLFj2H3wexLXvsHrU0
    - protonmail-verification=1c6c3ffc03087a7d17a7622423d3692d93815e0d
    - v=spf1 include:_spf.protonmail.ch mx ~all
_discord:
  ttl: 0
  type: TXT
  value: dh=ced56c4489ad0f0bce4556f6430c19a3ecfbdb66
_dmarc:
  ttl: 0
  type: TXT
  value: v=DMARC1\; p=none
_github-challenge-dysnomia-studio:
  ttl: 0
  type: TXT
  value: 231b2aaa08
alchemistry-leaderboard:
  ttl: 0
  type: CNAME
  value: dysnomia.studio.
blog:
  ttl: 0
  type: CNAME
  value: dysnomia.studio.
bugs:
  ttl: 0
  type: CNAME
  value: dysnomia.studio.
carbon:
- ttl: 0
  type: A
  value: 188.165.200.10
- ttl: 0
  type: AAAA
  value: '2001:41d0:2:910a::1'
cloud:
  ttl: 0
  type: CNAME
  value: dysnomia.studio.
discord:
  ttl: 0
  type: CNAME
  value: dysnomia.studio.
leaderboard:
  ttl: 0
  type: CNAME
  value: dysnomia.studio.
nitrogen:
- ttl: 0
  type: A
  value: 37.187.74.34
- ttl: 0
  type: AAAA
  value: '2001:41d0:a:2a22::1'
oxygen:
- ttl: 0
  type: A
  value: 176.9.116.19
- ttl: 0
  type: AAAA
  value: '2a01:4f8:151:64ec::2'
'prd.manufacturinc':
  ttl: 0
  type: CNAME
  value: dysnomia.studio.
protonmail2._domainkey:
  ttl: 0
  type: CNAME
  value: protonmail2.domainkey.ducgpwqr2eyjqai73ymbh53s34wsmrkkidsbiaakuh2qa3f6yjraa.domains.proton.ch.
protonmail3._domainkey:
  ttl: 0
  type: CNAME
  value: protonmail3.domainkey.ducgpwqr2eyjqai73ymbh53s34wsmrkkidsbiaakuh2qa3f6yjraa.domains.proton.ch.
protonmail._domainkey:
  ttl: 0
  type: CNAME
  value: protonmail.domainkey.ducgpwqr2eyjqai73ymbh53s34wsmrkkidsbiaakuh2qa3f6yjraa.domains.proton.ch.
'ptb.manufacturinc':
  ttl: 0
  type: CNAME
  value: dysnomia.studio.
sonar:
  ttl: 0
  type: CNAME
  value: dysnomia.studio.
status:
  ttl: 0
  type: CNAME
  value: dysnomia-studio.github.io.
wiki:
  ttl: 0
  type: CNAME
  value: dysnomia.studio.
www:
  ttl: 0
  type: CNAME
  value: dysnomia.studio.
